### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by janikakalliokoski** [TeemuBergman/tiralabra23#1]
**Projekti ladattu 14.2. klo 17.52**

- Yritin käynnistää ohjelman ohjeiden mukaisesti, mutta ohjelma antaa suoraan luvun 29.0.
Huomautuksena se, että ohjelman voi myös käynnistää ajamalla komennon poetry run invoke start, ilman, että siirtyy virtuaaliympäristöön :)

- shunting-yard.py tiedostossa on kaksi funktiota, jotka liittyvät algoritmiin. Kannatan sitä, että teet luokan, jonka nimi on esimerkiksi ShuntingYard, ja siirrät luokkaan kaikki metodit mitkä liittyvät itse algoritmiin.

- Funktio shunting_yard on erittäin pitkä, ja sen voisi jakaa useampaan osaan. Yksi metodi voisi käsitellä aina yhtä tapahtumaa annetussa lausekkeessa, esim. Oma metodi sulkeiden käsittelyyn ja oma metodi operaattoreiden käsittelyyn. 

- En ole varma, lukeeko ohjelma vielä käyttäjältä syötteitä vai ei koska en saanut ohjelmaa käynnistettyä ohjeiden mukaisesti, mutta io-luokan tekeminen helpottaa käyttäjän syötteiden lukemista!

- Testejä on paljon, hyvä! shunting_yard funktio näyttää toimivan oikein. Kannattaa kokeilla myös paljon erilaisia virheellisiä syötteitä, kuten (2+2)) tai )2+3( jne., jotta voit varmistaa, että ohjelma pysähtyy virheellisillä syötteillä. Kokeilin myös itse ajaa testit, ja kaikki menivät läpi!

Jokatapauksessa hyvin menee :)

**Comment by TeemuBergman** [comment]
Kiitos hyvistä huomioista!

Olin tosiaan tähän asti kehittänyt projektia testaus edellä, joten varsinainen käyttöliittymä oli tässä vaiheessa vielä tekemättä. Siinä mielessä tämä oli ehkä hieman tylsä kokemus vertaisarvioida. 😁

Vinkkisi mukaisesti siirsin keskeiset funktiot omiin luokkiinsa ja refaktoroin niitä pienemmiksi funktioksi sekä metodeiksi. Kyllähän tuo kokonaisuutta selkeyttää, joka taas auttaa algoritmeissä vielä olevien ongelmien ratkomisessa.

Kiitokset vielä ja onnea myös oman projektisi parissa! 👍

**Comment by TeemuBergman** [comment]
Kiitos hyvistä huomioista!

Olin tosiaan tähän asti kehittänyt projektia testaus edellä, joten varsinainen käyttöliittymä oli tässä vaiheessa vielä tekemättä. Siinä mielessä tämä oli ehkä hieman tylsä kokemus vertaisarvioida. 😁

Vinkkisi mukaisesti siirsin keskeiset funktiot omiin luokkiinsa ja refaktoroin niitä pienemmiksi funktioksi sekä metodeiksi. Kyllähän tuo kokonaisuutta selkeyttää, joka taas auttaa algoritmeissä vielä olevien ongelmien ratkomisessa.

Kiitokset vielä ja onnea myös oman projektisi parissa! 👍
