### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by HeljaeRaeisaenen** [TeemuBergman/tiralabra23#2]
Projekti ladattu 24.2. klo 18.07

- Repositorio ja README näyttää todella hyvältä, ja käyttöohjeet löytyy helposti
- Mielestäni koodin seassa olevat kommenttirivit ovat turhia. Koodi on selkeää ja sen toiminnan voi ymmärtää lukemalla koodia. 
- Docstring-dokumentaatio on hyvää ja selkeää.
- Koodissa ei ole mitään mistä voisin huomauttaa :)

Ohjelmaa käyttäessä:
- Jos ohjelmalle syöttää vain sulun tai operaattorin ja painaa ‘=’-nappia, konsoliin tulostuu virheviesti. Samoin jos sulut jättää auki. Jonkinlainen virheidenkäsittely olisi hyvä.
- Jos Expression-kentässä olevan tekstin pyyhkii pois näppäimistöllä, teksti katoaa. Kun sen jälkeen sovelluksen nappien avulla lisää merkkejä, tulee pyyhitty teksti taas näkyviin. Tämä on kuitenkin aika pieni virhe joka piti etsimällä etsiä, joten älä stressaa liikaa jos sitä ei saa korjattua :D
- Muuten ohjelma näyttää oikein hyvältä, ja se näyttää myös lähes valmiilta, eli hyvin menee.

**Comment by TeemuBergman** [comment]
Kiitos palautteesta! 👍🏻 

Virheiden käsittelyä tuli laajennettua tästä versiosta sekä tuo käyttöliittymän bugi korjattua myös, eli kiitos näistä!
